version: "3.8"
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: SimpleNote
      POSTGRES_PASSWORD: 1111
    volumes:
      - ./db:/var/opt/mssql/data
    ports:
      - 5432:5432

  front:
    build: ./SimpleNoteFront
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.con
    depends_on:
      - db
    ports:
      - 80:80
